#### 反向积累
* 前向：执行图，存储中间结果
* 反向：从相反方向执行图，去除不需要的枝（如果有有导数的值不需要的话，就不需要计算）

In [11]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

#### 
在我们计算y关于x的梯度之前，我们需要一个地方来存储梯度。

In [12]:
x.requires_grad_(True)
x.grad

y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算y关于x每个分量的梯度。

In [13]:
y.backward()
x.grad


tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad == 4*x

tensor([True, True, True, True])

In [15]:
# 在默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad


tensor([1., 1., 1., 1.])

In [18]:
x.grad.zero_()

# 哈达玛积(Hadamard product)是矩阵的一类运算，若A=(aij)和B=(bij)是两个同阶矩阵，若cij=aij×bij,则称矩阵C=(cij)为A和B的哈达玛积，或称基本积
y = x*x
y.sum().backward()

x.grad


tensor([0., 2., 4., 6.])

In [19]:
x.grad.zero_()

y = x*x
# 把y当成一个常数
u = y.detach()

z = u*x
z.sum().backward()

x.grad == u


tensor([True, True, True, True])

In [20]:
x.grad.zero_()
y.sum().backward()
# y = x1*x1 + x2*x2 ........
# y' = 2*x1 ...........

x.grad == 2*x

tensor([True, True, True, True])